/* eslint-disable @next/next/no-img-element */
import Head from "next/head";

import { Group } from "models/Group";
import { useGroups } from "providers/Provider";
import { trpc } from "utils/trpc";

import ChatArea from "./ChatArea";
import Header from "./Header";
import LeftSidebar from "./LeftSidebar";

const EmptyChatArea = ({
  groups,
  selectedGroupId,
}: {
  groups: Group[] | undefined;
  selectedGroupId: string;
}) => {
  let content = null;

  if (!groups) return null;

  if (groups?.length === 0)
    content = (
      <div>
        <h2>You do not have any groups.</h2>
        <span>Please create a new group</span>
      </div>
    );
  else if (!selectedGroupId) content = <div>Please select group</div>;

  return <div className="grid w-full place-items-center px-5">{content}</div>;
};

export default function Home() {
  const { selectedGroupId } = useGroups();

  const { data: groups } = trpc.roomRouter.getGroups.useQuery();

  return (
    <main className="flex h-[100svh] flex-col rounded-lg shadow-lg ">
      <Head>
        <title>Next Pages router starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex flex-grow flex-row justify-between bg-white">
        <LeftSidebar />
        {selectedGroupId ? (
          <ChatArea />
        ) : (
          <EmptyChatArea groups={groups} selectedGroupId={selectedGroupId} />
        )}
      </div>
    </main>
  );
}
